# Generated by Django 6.1 on 2026-08-19 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testseries', '0002_testresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='testresult',
            name='user_answers',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
